### PR TITLE
add composer.lock & update travis config

### PR DESCRIPTION
**Pull request by stefanotorresi**
as per zendframework/zendframework#7660

also entails these changes:
- bump minimum php version to 5.6
- bump minimum phpunit version to 4.8
- add composer scripts entries
- fix coveralls configuration
- fix travis.yml env variables to not be affected by travis-ci/travis-ci#1444
- remove obsolete phpunit bootstrap

### CODE REVIEW

**Comment by malukenho** [comment]
Why to commit `composer.lock` here?

**Comment by stefanotorresi** [comment]
hmm? is there any reason why this component should not be consistent with the others in this regard?

**Comment by malukenho** [comment]
actually there's other components that still missing `composer.lock` if that is the case.

**Comment by stefanotorresi** [comment]
zendframework/zendframework#7660 is exactly the thing I'm working on to bring order in this chaos.  ;-)

**Comment by malukenho** [comment]
Oh! I see @stefanotorresi

**Pull request closed without merging**
